'use strict';
var browserify, express, routes, config, app, application;
browserify = require('browserify-middleware');
express = require('express');
config = require('./config');
routes = require('./modules/routes').routes();
app = express();
config.configure(app, express, browserify);
routes.initialize(app);
application = app.listen(3333);
